name: "social_media_penetration"
version: "1.0"
config-version: 2

profile: clickhouse_ftw
model-paths: ["models"]
macro-paths: ["macros"]

models:
  social_media_penetration:
    clean:
      +schema: clean_grp2
      +materialized: table
    mart:
      +schema: mart_grp2
      +materialized: view
    
